## 1   (Camera Models- 20 points)  Prove that the vector from the viewpoint of a pinhole camera to the vanishing point (which is a point on the imageplane) of a set of 3D parallel lines in space is parallel to the direction of that set parallel lines. Please show steps of your proof.

Hint: You can either use geometric reasoning or algebraic calculation. 
If you choose to use geometric reasoning, you can use the fact that the projection of a 3D line in space is the intersection of its “interpretation
plane” with the image plane.  Here the interpretation plane (IP) is a plane passing through the 3D line and the center of projection (viewpoint) of the
camera.  Also, the interpretation planes of two parallel lines intersect in a line passing through the viewpoint, and the intersection line is parallel to
the parallel lines.
If you select to use algebraic calculation, you may use the parametric representation of a 3D line: P = P0 +tV, where P= (X,Y,Z)  is any point on the
line (here    denote for transpose),   P0 = (X0,Y0,Z0)  is a given xed point on the line, vector V = (a,b,c)  represents the direction of the line, and t is
the scalar parameter that controls the distance (with sign) between P and P0.

### [SOLUTION 1](http://www.cs.toronto.edu/~jepson/csc420/notes/imageProjection.pdf)
Let $$\textbf{P}_w = \textbf{P_0} + t\textbf{V}$$ 

Where **P** is a vector representing a point from the image plane to a vanishing point in 3D-space. The vector **V** represent a line to point *P(a,b,c)* that is in the direction to the vanishing point.

$$\begin{bmatrix}a \\ b \\ c\end{bmatrix}$$ 



All lines parallel to **V** converge as the scalar value *t* goes to infinity i.e.

$$ \lim_{t \to \infty} \textbf{P}_w = \textbf{V} $$ 

for any parallel point in 3D space: for it shares the same vector V for corresponding starting point **P<sub>w,image</sub>** in the image plane.

For **P** in the perspective projection space we have the formulation **P= R•P<sub>w</sub>+T**, where **T<sub>3x1</sub>** is constant. Note **R<sub>3x3</sub>** can be found from $[\bar{vp_{1,1x3}}, \bar{vp_{2,1x3}}, \bar{vp_{3,1x3}}]^T$ where $\bar{vp_i}$ are normalized vanish points formed from three sets of parallel lines mutually orthogonal to one another.

Let $P_{w}'= P+\Delta P_0 + t V + \Delta V$, be a parallel line

$V= [a,b,c]^T$, where $tV$ forms a vanish point in perspective space

$\Delta P_{0;i,j} || \Delta V_{0;i,j}$, form a  parallel line

$P_{w}'= P + tV + (\Delta P_0 + \Delta V)$

Then $P' = R[(P_0 + t V) + (\Delta P_0 + \Delta V)] + T$, where $(\Delta P_0 + \Delta V) \equiv \Delta P_w'$

$P' = R[(P_0 + t V)] + R\Delta P_w' + T$, where $R • \Delta P_w' \equiv \Delta T$

$P' = R[(P_0 + t V)] + \Delta T + T$

$\textbf{P'} = \textbf{P} + \Delta \textbf{T} $ **(Eq 1)**

The line formed from the pinhole to the vanish point in world coordinates can be represented by the following:

$\Delta V - P'$, using vector notation: head minus tail

$\Delta V - P' = \Delta V  - (P +\Delta T) = \Delta V  - (P + R(\Delta P_0 + \Delta V))$

Recall, $R$ can be formed by the normalized vanish points therefore its cross product with $\Delta V$ turns one its rows to zero, 

similarly $\Delta P_0$ is parallel to $\Delta V$, so $R$ cross $\Delta P_0$ turn that $R$ row to zero

We have $\Delta V - P' = \Delta V  - P - R (\Delta P_0 + \Delta V)$, interpreting matrix orientation we have

$\Delta V - P' = \Delta V  - P - (R - [0, 0, f]^T)$, and $(R - [0, 0, f]^T)$ is a translation of between the image plane and focal plane. Droping the $\Delta V$ from both sides, by definition we have:

$ \textbf{- P'} =  \textbf{-P} - \textbf{P}_\textbf{w}•\textbf{T}$, **substituting** (Eq 1) we get 

$\Delta T = P_w•T$, where we know $\Delta T = R • \Delta P_w'$ and $\Delta P_w' || P$

$R • \Delta P_w' = P_w•T$ We have individual components on either side of the matrices parallel as a property


... the 3D line formed from the pinhole to a vanish point in the perspective plane is parallel to the set of 3D lines which forms that vanish point. 



### [SOLUTION 2](https://en.wikipedia.org/wiki/Vanishing_point)

![geo](https://github.com/adomakor412/ComputerVision/blob/master/CameraCalibration/images/Geometric.png?raw=true)

1. A set of 3D parallel lines form respect lines in the perspective plane.
2. Those lines in the perspective plane intersect forming a vanish point.
3. The 3D line projected from the pinhole to the vanish point is parallel to the set of parallel lines


# 2. (Camera Models- 20 points) Show that relation between any image point (xim, yim)   (in the form of (x1,x2,x3)  in projective space ) of a planar surface in 3D space and its corresponding point (Xw, Yw, Zw)  on the plane in 3D space can be represented by a 3×3 matrix. 

You should start from the general form of the camera model (x1,x2,x3)  = M M (Xw, Yw, Zw, 1) , where the image center (ox, oy), the focal length f, the scaling factors(
sx and sy),  the rotation matrix R and the translation vector T are all unknown. Note that in the course slides and the lecture notes, I used a
simplied model of the perspective project by assuming ox and oy are known and sx = sy =1, and only discussed the special cases of a plane. So you
cannot directly copy those equations I used.  Instead you should use the general form of the projective matrix, and the  general form of a plane
n  X  + n  Y  + n  Z   = d. 

### [SOLUTION](https://www.cis.upenn.edu/~jean/gma-v2-chap5.pdf)

$$\begin{bmatrix}
           x_{im} \\
           y_{im}
         \end{bmatrix}
         =
         \begin{bmatrix}
           u_{i}/w_{i} \\
           v_{i}/w_{i}
         \end{bmatrix}
         <=
         \begin{bmatrix}
           x_{1} \\
           x_{2} \\
           x_{3}
         \end{bmatrix}
         =
         \begin{bmatrix}
           u_{i} \\
           v_{i} \\
           w_{i}
         \end{bmatrix}
         =
         \textbf{M} 
         \begin{bmatrix}
           X_{i} \\
           Y_{i} \\
           Z_{i} \\
           1
         \end{bmatrix}
$$

$$(x_{im},y_{im}) \text{ is the image point in image (frame) coordinates derived from the perspective projection matrix: } (u_{i},v_{i},w_{i}).$$


$$(X_{i},Y_{i},Z_{i}) \text{ is the object in world coordinates.}$$


Notice, in the world coordinates there is the projective space of the object. Notice there is a 1 appended to the 3D world vector. This is to account for any shift in the apparatus when converting to the image. The shifts are absorbed in the projective matrix: **M = M<sub>int</sub> * M<sub>ext</sub>**.

The intrinsic parameters accounts for the principal point *(o<sub>x</sub>,o<sub>y</sub>)* and scaling factors *(s<sub>x</sub>,s<sub>y</sub>)* and noted as so:

**M<sub>int</sub>**=$$\begin{bmatrix}-f_{i} & 0 & o_{x} \\0 & -f_{i} & o_{y} \\0 & 0 & 1\end{bmatrix}$$

The extrinsic paramaters account for rotations and tranpositions:

**M<sub>ext</sub>**=$$\begin{bmatrix}r_{11} & r_{12} & r_{13} & T_{x} \\r_{21} & r_{22} & r_{23} & T_{y} \\r_{31} & r_{32} & r_{33} & T_{z} \end{bmatrix}$$

and all together:

**M**=
$$\begin{bmatrix}-f_{x}r_{11}+o_{x}r_{31}&-f_{x}r_{12}+o_{x}r_{32}&-f_{x}r_{13}+o_{x}r_{33}&-f_{x}T_{x}+o_{x}T_{z} \\-f_{y}r_{21}+o_{y}r_{31}&-f_{y}r_{22}+o_{y}r_{32}&-f_{y}r_{23}+o_{x}r_{33}&-f_{y}T_{y}+o_{y}T_{z} 
\\r_{31}&r_{32}&r_{33}&T_{z}
\end{bmatrix}$$

Lastly, recalling alignment from the optical axis anaology in the camera model, we implement a scale factor

$$\gamma = \begin{vmatrix}R_{3}^{T}\end{vmatrix}$$ such that

$$\hat{\textbf{M}}= \gamma \textbf{M}$$

From our plane equation we also have 

$$n_x X_w + n_y Y_w + n_z Z_w = d$$

Define $M$ such that $[X, Y, Z]^T = M•[X_w, Y_w, Z_w]^T$. Consider the fourth column of $M$, we have:

$$\hat{M}$$ =
$$\begin{bmatrix}-f_{x}r_{11}+o_{x}r_{31}&-f_{x}r_{12}+o_{x}r_{32}&-f_{x}r_{13}+o_{x}r_{33} \\-f_{y}r_{21}+o_{y}r_{31}&-f_{y}r_{22}+o_{y}r_{32}&-f_{y}r_{23}+o_{x}r_{33}
\\r_{31}&r_{32}&r_{33}
\end{bmatrix} + \gamma \begin{bmatrix}
           n_x(-f_{x}T_{x}+o_{x}T_{z}) \\
           n_y(-f_{y}T_{y}+o_{y}T_{z}) \\
           n_z(T_{z})
         \end{bmatrix} \begin{bmatrix}
           1/x_{1} \\
           1/x_{2} \\
           1/x_{3}
         \end{bmatrix}$$
         

Where $$ d =\begin{bmatrix}
           n_{x} \\
           n_{y} \\
           n_{z}
         \end{bmatrix}\begin{bmatrix}
           1/x_{1} \\
           1/x_{2} \\
           1/x_{3}
         \end{bmatrix}$$
         
Therefore $$\gamma = 1/d$$


### 3.  (Calibration- 20 points )  Prove the Orthocenter Theorem by geometric arguments: Let T be the triangle on the image plane dened by the threevanishing points of three mutually orthogonal sets of parallel lines in space. Then the image center is the orthocenter of the triangle T 
(i.e., the
common intersection of the three altitudes.  Note that you are asked to prove the Orthocenter Theorem rather than that the orthocenter itself as
the common interaction of the three altitudes, which you can use as a fact. 
(1)    Basic proof: use the result of Question 1, assuming the aspect ratio of the camera is 1. (10 points)
(2)    If you do not know the  focal length of the camera, can you still nd the image center using the Orthocenter Theorem? Can you further
estimate the focal length? For both questions, please show why (and then how) or why not. (5 points)
(3)    If you do not know the aspect ratio of the camera, can you still nd the image center using the Orthocenter Theorem? **Show why or why
not**. (5 points)

### [SOLUTION](https://www.youtube.com/watch?v=HSGM5o_WWlc)

For the Orthocenter theorem we use a logical proof. (It is an if and only if proof.)

![pinholeCM](https://github.com/adomakor412/ComputerVision/blob/master/CameraCalibration/images/pinoleCM.png?raw=true)

Recall from the pinhole camera model that the image center is along the optical axis. We see that the focal point for all parallel points on an object plane will have the same Field of View (FOV) (angles) in the perspective projection. Consider the equivalent mathematical model where the image plane is moved to the focal plane. (Notice that the image center and the focal node are now one in the same.)

![EquivalentGeometry](https://github.com/adomakor412/ComputerVision/blob/master/CameraCalibration/images/EquivalentGeometry.png?raw=true)

The property we see for the pinhole camera model is that for a set of three mutual parallel lines, the [ProspectiveTransformation](https://github.com/adomakor412/ComputerVision/blob/master/CameraCalibration/images/ProspectiveTransformation.png?raw=true) has parallel lines intersect forming vanishing points. 

![ProspectiveTransformation](https://github.com/adomakor412/ComputerVision/blob/master/CameraCalibration/images/ProspectiveTransformation.png?raw=true)

The FOV for these vanishing points are taken at infinity therefore the angle is 90° taken at the limit. Note that these vanishing points are outside the image view.

![FocalLengthFOV](https://github.com/adomakor412/ComputerVision/blob/master/CameraCalibration/images/FocalLengthFOV.png?raw=true)

The physical length of these vanishing points form lines of altitude to the optical axis(AH, CH, BH). Form a triangle from these three vanishing points (triangle ABC). Form a circle from these three vanishing points (circle ABC [not drawn]). Locate the corresponding circumcenter (O) of this circle on the focal plane. This corresponds to the circumcenter on the image plane. Connect the circumcenter to the intersection point formed from lines of altitude (OH). 

Since the image center is defined as the point that corresponds to the connection of the focal plane to the image plane on the optical axis, the image center is the orthocenter.

#### Estimating orthocenter

You don't need to know the focal length to obtain image center. You don't need to solve for 8 points from the matrix theorem:
![ProjectionMatrixMethod](https://github.com/adomakor412/ComputerVision/blob/master/CameraCalibration/images/ProjectionMatrixMethod.png?raw=true)
Instead, you can use the orthocenter theorem to estimate the image center.

#### Finding the aspect ratio and estimating the focal length.

Without the aspect ratio you are unable to find the focal length because you're unable to map between the extrinsic and intrinsic values.



### 4. Calibration Programming Exercises (40 points): Implement the direct parameter calibration method in order to 
(1) learn how to use SVD to solve systems of linear equations; 

(2) understand the physical constraints of the camera parameters; and 

(3) understand important issues related to
calibration, such as calibration pattern design, point localization accuracy and robustness of the algorithms. Since calibrating a real camera involves
lots of work in calibration pattern design, image processing and error controls as well as solving the equations, we will mainly use simulated data to
understand the algorithms.  As a by-product we will also learn how to generate 2D images from 3D models using a “virtual” pinhole camera. The
calibration procedure has the following three steps:

**1.** Calibration pattern “design”. Generate data of a “virtual” 3D cube similar to the one shown in here of the lecture notes in camera calibration. For
example, you can hypothesize a 1x1x1 m  cube and pick up the coordinates of 3-D points on corners of each black square in your world coordinate
system. Make sure that your data is sucient for the following calibration procedures. In order to check the correctness of your data, draw your
cube (with the control points marked) using Matlab (or whatever tools you are selecting). I have provided a piece of starting code in Matlab for you
to use.

**2.** A “virtual” camera and its images. Design a “virtual” camera with known intrinsic parameters including focal length f, image center (o , o ) and
pixel size (s , s ).  As an example, you can assume that the focal length is f = 16 mm, the image frame size is 512*512 (pixels) with (o ,o ) = (256, 256),
and the size of the image sensor  inside your camera is 8.8 mm *6.6 mm (so the pixel size is (s ,s ) = (8.8/512, 6.6/512) ). Capture an image of your
“virtual” calibration cube with your virtual camera in a given pose (i.e., R and T).  For example, you can take the picture of the cube 4 meters away
and with a tilt angle of 30 degree. Use three rotation angles alpha, beta, gamma to generate the rotation matrix R (refer to the lecture notes in
camera model – please check the correctness of the R equation especially for signs).  You may need to try dierent pose in order to have a suitable
image of your calibration target. In your report, please clearly list the parameters you used for generating your calibration image. They are called
the “ground truth” of the parameters.

**3.** Direction calibration method: Estimate the intrinsic (f , f , aspect ratio a, image center (o ,o ) ) and extrinsic (R, T and further alpha, beta, gamma)
parameters. Use SVD to solve the homogeneous linear system and the least square problem, and to enforce the orthogonality constraint on the
estimate of R.  You are asked to do the following:
        
**i.**      Use the accurately simulated data (both 3D world coordinates and 2D image coordinates) to the algorithms, and compare the results with
the “ground truth” data (which are given in step (a) and step (b)).  Remember you are practicing a camera calibration, so you should pretend you
know nothing about the camera parameters (i.e. you cannot use the ground truth data in your calibration process). However, in the direct
calibration method, you could use the knowledge of the image center (in the homogeneous system to nd extrinsic parameters) and the aspect
ratio (in the Orthocenter theorem method to nd image center). 

**ii.**      Show experimentally whether the unknown aspect ratio matters in estimating the image center, and how the initial estimation of image
center aects the estimating of the remaining parameters.  Give a solution to solve the problems if any and implement it.

**iii.**      Accuracy Issues. Add in some random noises to the simulated data and run the calibration algorithms again. See how the “design tolerance”
of the calibration target and the localization errors of 2D image points aect the calibration accuracy. For example, you can add 0.5 mm random
error to 3D points and 1.0 pixel random error to 2D points. Also analyze how sensitive of the Orthocenter method is to the extrinsic parameters in
imaging the three sets of the orthogonal parallel lines. (* extra points:10)
In all of the steps, you should give you results using either tables or graphs, or both of them.

### Solution

![CalibrationPattern](http://ccvcl.org/wp-content/uploads/2019/10/calibrationpattern.gif)


#### [Ground truth parameters](https://apple.stackexchange.com/questions/267746/what-is-the-focal-length-of-the-iphone-7s-camera-when-accounting-for-video-crop)
focal length is **16** mm.

<ins>image frame size</ins> is **512x512** (pixelation) with (o<sub>x</sub>,o<sub>y</sub>) = **(256, 256)**,

image sensor inside camera is **8.8 mm. x 6.6 mm.** (so the pixel size is (s<sub>x</sub>,s<sub>y</sub>) = (0.0172 mm per pixel, 0.13 mm per pixel) ).

#### [Direct Calibration Method](https://www.pyimagesearch.com/2015/01/19/find-distance-camera-objectmarker-using-python-opencv/)

Estimate the intrinsic parametes (f<sub>x</sub> , f<sub>y</sub>, aspect ratio a, image center (o<sub>x</sub> ,o<sub>y</sub>) )

extrinsic parameters (R, T and further alpha, beta, gamma). 

Use SVD to solve the homogeneous linear system and the least square problem, and to enforce the orthogonality constraint on the estimate of R. 

For the chosen points A we solve [U,S,V] = svd(A) to obtain V:

**A =**

#### ![A](https://github.com/adomakor412/ComputerVision/blob/master/CameraCalibration/images/A.png?raw=true)

**V =**
#### ![V](https://github.com/adomakor412/ComputerVision/blob/master/CameraCalibration/images/V.png?raw=true)

**R =**
#### ![V](https://github.com/adomakor412/ComputerVision/blob/master/CameraCalibration/images/V.png?raw=true)

**T =**
#### ![V](https://github.com/adomakor412/ComputerVision/blob/master/CameraCalibration/images/V.png?raw=true)

In [12]:
import camera
import numpy as np
import cv2 as cv

file = "images/QueensGambit.jpeg"
image = cv.imread(file)

# load points
shape = np.shape(image)
P = np.array(image)#.T
P_prime = P.reshape(shape[2],shape[0],shape[1])
P_prime_CT = P.reshape(shape[2],shape[1],shape[0])
#points = np.vstack((points,np.ones(points.shape[1])))

# setup camera
print(np.matmul(P_prime,P_prime_CT))
# print(np.dot(P,P_prime))


# cam = camera.Camera(P)
# x = cam.project(points)

# plot projection
plt.figure()
plt.plot(x[0],x[1],'k.')
plt.show()

[[[  9  10 196 ... 160 143  88]
  [109 131 231 ...  23   2  13]
  [114 183 164 ...  59 188 248]
  ...
  [ 13 111 194 ... 191  98  87]
  [ 29 167 163 ... 223  37 244]
  [ 98 223  99 ... 113  50  69]]

 [[103 167  98 ... 192 115 252]
  [230  78  15 ...  36 216 143]
  [104  92 186 ... 200  72  14]
  ...
  [ 23 177  23 ...  17 133  49]
  [249  23 190 ... 149 237 164]
  [128 220  71 ...  16  50  21]]

 [[ 80 234 180 ... 233  53  10]
  [ 18 100   6 ...  66 233  29]
  [ 61 217 140 ...  26  18 250]
  ...
  [ 92 199  63 ... 133 142  43]
  [251 211 218 ... 185 129 198]
  [251  29  45 ... 228  52 118]]]


NameError: name 'figure' is not defined

In [2]:
import DirectCalibration as DC


KNOWN_DISTANCE = 8.5 #inches

KNOWN_WIDTH = 4032*1.42 #inches
'''
load the first image that contains an object that is KNOWN TO BE 1 feet
from our camera, then find the paper marker in the image, and initialize
the focal length
'''

print(len(image))

f = DC.findFocalLength(KNOWN_DISTANCE,KNOWN_WIDTH,image)
print(f)
print(f/(1.89))
print(f/(1.42))


error: OpenCV(4.4.0) /private/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/pip-req-build-4jcifzim/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'


### [Factoring The Camera Matrix](https://culturalengineerassociation.weebly.com/uploads/8/6/7/7/86776910/programming_computer_vision_with_python.pdf)

The estimation is close to ground truth. The estimated focal length is 0.39 inches, 92.3% accuracy with  f_x,e = 0.21 and f_y,e = 0.28. The estimated aspect ratio is 0.75.

In [ ]:
import numpy as np
import glob
# termination criteria
criteria = (cv.TERM_CRITERIA_EPS + cv.TERM_CRITERIA_MAX_ITER, 30, 0.001)
# prepare object points, like (0,0,0), (1,0,0), (2,0,0) ....,(6,5,0)
objp = np.zeros((6*7,3), np.float32)
objp[:,:2] = np.mgrid[0:7,0:6].T.reshape(-1,2)
# Arrays to store object points and image points from all the images.
objpoints = [] # 3d point in real world space
imgpoints = [] # 2d points in image plane.
images = glob.glob('images/*')
#print(len(images))
for fname in images:
    img = cv.imread(fname)
    gray = cv.cvtColor(img, cv.COLOR_BGR2GRAY)
    # Find the chess board corners
    ret, corners = cv.findChessboardCorners(gray, (7,6), None)
    # If found, add object points, image points (after refining them)
    if ret == True:
        objpoints.append(objp)
        corners2 = cv.cornerSubPix(gray,corners, (11,11), (-1,-1), criteria)
        imgpoints.append(corners)
        # Draw and display the corners
        cv.drawChessboardCorners(img, (7,6), corners2, ret)
        cv.imshow('img', img)
        
        cv.waitKey(500)
        print(cv.calibrateCamera(objpoints, imgpoints, gray.shape[::-1], None, None))
        
        print('hello')
cv.destroyAllWindows()

In [7]:
#import scipy
ret, mtx, dist, rvecs, tvecs = cv.calibrateCamera(objpoints, imgpoints, gray.shape[::-1], None, None)

NameError: name 'gray' is not defined